namespace Sample
{
    runtimeclass SampleControl : Microsoft.UI.Xaml.Controls.ContentControl
    {
        SampleControl();
        static Microsoft.UI.Xaml.DependencyProperty LabelProperty{ get; };
        String Label;
    }
}
